version: "3.7"
services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    container_name: lisco_front
    volumes:
      - /front/node_modules
    depends_on:
      - server
      
  server:
    build: ./server
    ports:
      - "3001:3001"
    container_name: lisco_server
    volumes:
      - /server/node_modules
    